# Generated by Django 3.2.6 on 2021-10-12 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=64, verbose_name='страна')),
            ],
            options={
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='CountryRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=64, verbose_name='регион страны')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_region', to='mainapp.country')),
            ],
            options={
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(verbose_name='ваш возраст')),
                ('skills', models.CharField(max_length=256, verbose_name='ваши навыки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='имя на портале')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64, validators=[mainapp.models.validate_field], verbose_name='Название товара')),
                ('product_grade', models.CharField(blank=True, max_length=128, validators=[mainapp.models.validate_field], verbose_name='Марка товара')),
                ('product_year', models.PositiveIntegerField(blank=True, choices=[(2020, 2020), (2019, 2019), (2021, 2021), (2018, 2018)], null=True, verbose_name='Год изготовления')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_product', to='mainapp.country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_product', to='mainapp.countryregion')),
            ],
            options={
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
