# Generated by Django 3.2.6 on 2021-08-12 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=64, verbose_name='страна')),
            ],
            options={
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='CountryRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=64, verbose_name='регион страны')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.country')),
            ],
            options={
                'verbose_name_plural': 'Регионы страны',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64, verbose_name='Название товара')),
                ('product_grade', models.CharField(blank=True, max_length=128, verbose_name='Марка товара')),
                ('product_year', models.PositiveIntegerField(blank=True, choices=[('2020', 2020), ('2019', 2019), ('2021', 2021), ('2018', 2018)], verbose_name='Год изготовления')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.countryregion')),
            ],
            options={
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
