# Generated by Django 3.2.6 on 2021-08-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_year',
            field=models.PositiveIntegerField(blank=True, choices=[('2021', 2021), ('2019', 2019), ('2020', 2020), ('2018', 2018)], verbose_name='Год изготовления'),
        ),
    ]
