# Generated by Django 3.2.6 on 2021-08-17 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_product_product_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_grade',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Допускается только кирилица или латиница. Допускается два слова.', regex='^[a-zA-Zа-яА-Я]+|[a-zA-Zа-яА-Я]+$')], verbose_name='Марка товара'),
        ),
    ]
