# Generated by Django 3.2.6 on 2021-08-23 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_product_product_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryregion',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_region', to='mainapp.country'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_product', to='mainapp.country'),
        ),
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_product', to='mainapp.countryregion'),
        ),
    ]
